owner: subnoto # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
    - name: Subnoto
      url: https://subnoto.com

status-website:
    cname: status.subnoto.com
    # baseUrl: /your-repo-name
    logoUrl: https://raw.githubusercontent.com/subnoto/upptime/master/assets/subnoto-logo.png
    favicon: https://subnoto.com/favicon.ico
    themeUrl: https://status.subnoto.com/custom-theme.css
    name: Status
    introTitle: "Subnoto Status Page"
    introMessage: "Follow our status updates on this page."
    navbar:
        - title: Status
          href: /
        - title: Website
          href: https://subnoto.com
        - title: GitHub
          href: https://github.com/$OWNER/$REPO

assignees:
    - Mikescops
    - tidalf
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
